app:
    resource: '@AppBundle/Controller/'
    type:     annotation

app_users:
    resource: '@UserBundle/Controller/'
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

